spring:
    application:
        name: acutity
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/acuity
        username: root
        password: root
    jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      show-sql: false
server:
    port: 8080